name: "Apply Stack after PR is Merged"

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  issues: read

env:
  ARM_ACCESS_KEY: "${{ secrets.ARM_ACCESS_KEY }}"
  ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"

jobs:
  terraform-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate module and provider bindings
        run: npm run get

      - name: Synthethize
        run: npm run synth

      - name: Archive cloud formation
        uses: actions/upload-artifact@v3
        with:
          name: tf
          path: cdktf.out/stacks/gab-cdk/cdk.tf.json

  terraform-deploy:
    needs: terraform-synth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Download Terraform Synth
        uses: actions/download-artifact@v3
        with:
          name: tf

      - name: Install dependencies
        run: npm ci

      - name: Generate module and provider bindings
        run: npm run get

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.4.4
          cdktfVersion: 0.15.5
          stackName: gab-cdk
          mode: auto-approve-apply
          githubToken: ${{ secrets.GITHUB_TOKEN }}
